name: latest youtube videos
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day, on the day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest youtube videos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCeiC2G8vcz6tBmvVo8ydMgQ"